name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: 🛎️ Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history for branches and tags

      - name: 🍞 Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📂 Install Dependencies
        run: bun install

      - name: 🏗️ Build Project
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SES_SOURCE_EMAIL: ${{ secrets.SES_SOURCE_EMAIL }}
        run: bun run --bun build

      - name: 💰 Profit
        run: echo 🐞
